### ISSUE TITLE
install focal version on ubuntu 20.4

### ISSUE THREAD

**Issue by swa2050** [rajannpatel/ubuntupbx#2]
![error](https://user-images.githubusercontent.com/122435442/211751320-c6e0921c-f207-4e9e-bf91-a78c28205e71.JPG)

ass shown error message and cant run

**Comment by rajannpatel** [comment]
Installing the PM2 and Framework modules first resolves this issue. Thank you for reporting it! Please reopen the ticket if this fix does not solve your problem.

**Comment by rajannpatel** [comment]
[b4e3f80](https://github.com/rajannpatel/ubuntupbx/commit/b4e3f8012de92e7d266e83936e4e5c4a4390aefb) solves this issue

**Comment by rajannpatel** [comment]
The latest https://github.com/rajannpatel/ubuntupbx/blob/main/jammy/install.sh does not have this issue
